# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Setup certificates and profiles"
  lane :certificates do
    # Setup certificates for App Store distribution
    match(type: "appstore")
  end

  desc "Generate new certificates and profiles (first time setup)"
  lane :setup_match do
    # Generate certificates and profiles for the first time
    match(
      type: "appstore",
      force: true,
      force_for_new_devices: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Setup certificates and provisioning profiles
    match(type: "appstore")
    
    # Increment build number
    increment_build_number(xcodeproj: "Invoicer.xcodeproj")
    
    # Build the app
    build_app(
      scheme: "Invoicer",
      workspace: nil,
      project: "Invoicer.xcodeproj",
      export_method: "app-store",
      output_directory: "./fastlane/builds",
      clean: true,
      codesigning_identity: "iPhone Distribution",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "come.nicolasbarb.filea" => "match AppStore come.nicolasbarb.filea"
        }
      }
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false
    )
  end

  desc "Build app for release"
  lane :build do
    # Increment build number
    increment_build_number(xcodeproj: "Invoicer.xcodeproj")
    
    # Build the app
    build_app(
      scheme: "Invoicer",
      workspace: nil,
      project: "Invoicer.xcodeproj",
      export_method: "app-store",
      output_directory: "./fastlane/builds"
    )
  end

  desc "Generate screenshots"
  lane :screenshots do
    capture_screenshots
  end

  desc "Deploy to App Store"
  lane :release do
    # Build the app
    build
    
    # Upload to App Store
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true
    )
  end
end